### ISSUE TITLE
[error] data is not defined

### ISSUE THREAD

**Issue by websterguy** [mclemente/party-overview#26]
When pressing the keybind to open, I get the following error:
```
foundry.js:316 ReferenceError: An error occurred while rendering PartyOverviewApp 2: data is not defined
    at PartyOverviewApp.update (logic.js:63:5)
    at PartyOverviewApp.getData (logic.js:109:8)
    at PartyOverviewApp._render (foundry.js:3059:29)
    at PartyOverviewApp.render (foundry.js:3018:10)
    at PartyOverviewApp.render (logic.js:143:9)
    at Object.onDown (party-overview.js:17:18)
    at Function._executeKeybind (foundry.js:1623:66)
    at KeyboardManager._processKeyboardContext (foundry.js:1662:33)
    at KeyboardManager._handleKeyboardEvent (foundry.js:1700:10)
    at foundry.js:1357:56
```

Playing pf2e 3.2.2.10054 on V9.242, no other mods

**Comment by mclemente** [comment]
Thanks, should be fixed now.
