### ISSUE TITLE
Can't load actor after upgrade to version 10

### ISSUE THREAD

**Issue by jburrows127** [mclemente/party-overview#57]
After I upgraded to version 10 of Foundry and updated Party Overview (PO), PO no longer functions with the following error types appearing in the console log. Reinstalling didn't resolve the issue, and I'm not sure how to resolve this.

logic.js:50 Error: Couldn't load actor 'Bob' (ID: '8dfAB53nPlujHL00') ReferenceError: obj is not defined
    at dnd5eProvider.getActorDetails (SystemProvider.js:576:76)
    at logic.js:48:46
    at Array.map (<anonymous>)
    at PartyOverviewApp.update (logic.js:46:19)
    at PartyOverviewApp.getData (logic.js:112:8)
    at PartyOverviewApp._render (foundry.js:5067:29)
    at PartyOverviewApp.render (foundry.js:5026:10)
    at PartyOverviewApp.render (logic.js:155:9)
    at HTMLButtonElement.<anonymous> (party-overview.js:62:17)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

foundry.js:747 TypeError: Cannot read properties of undefined (reading 'acr')
[Detected 1 package: party-overview]
    at SystemProvider.js:417:21
    at Array.map (<anonymous>)
    at Object.<anonymous> (SystemProvider.js:415:18)
    at Object.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:13:259)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at handlebars.min.js:27:7554
    at Array.forEach (<anonymous>)
    at handlebars.min.js:27:7522
    at Object.<anonymous> (handlebars.min.js:27:7597)
    at Object.c (handlebars.min.js:27:19853)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:17:49)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at Object.h (handlebars.min.js:27:18738)
    at Object.c [as invokePartial] (handlebars.min.js:27:15036)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:67:28)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at renderTemplate (foundry.js:6906:10)
    at async PartyOverviewApp._renderInner (foundry.js:5230:16)
    at async PartyOverviewApp._render (foundry.js:5073:19)

**Comment by mclemente** [comment]
Do you get any errors when opening Bob's character sheet? It looks like his biography is somehow broken.

Could you export that character's data and send it here?

**Comment by jburrows127** [comment]
There are no errors when I open Bob's sheet. Attached is the export of his character sheet. Thanks for looking into this!
[fvtt-Actor-bob.zip](https://github.com/mclemente/party-overview/files/9996335/fvtt-Actor-bob.zip)

**Comment by mclemente** [comment]
Thanks. Just update the module and it should work now.
