### ISSUE TITLE
Update 2.15.9 does not open the Party Overview in 13th Age system

### ISSUE THREAD

**Issue by NikolaSama** [mclemente/party-overview#63]
As the title says. It doesn't work in the latest 4 updates at the very least. However, I reverted to version 2.15 and it seems to work then.

**Comment by mclemente** [comment]
Were there any errors on the console? I just created a new world and there were no issues. The logic for 13th Age hasn't been touched for over a year now.

**Comment by NikolaSama** [comment]
Right, hello again. Probably should've involved that info from the beginnning.
This is what I get when I have all modules enabled:
`Foundry VTT | Rendering PartyOverviewApp
logic.js:50 Error: Couldn't load actor 'Crumbling Skeleton' (ID: 'P3t8OSl4HhWS0UZl') TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at archmageProvider.getActorDetails (SystemProvider.js:134:10)
    at logic.js:48:46
    at Array.map (<anonymous>)
    at PartyOverviewApp.update (logic.js:46:19)
    at PartyOverviewApp.getData (logic.js:112:8)
    at PartyOverviewApp._render (foundry.js:5108:29)
    at PartyOverviewApp.render (foundry.js:5067:10)
    at PartyOverviewApp.render (logic.js:159:9)
    at HTMLButtonElement.<anonymous> (party-overview.js:62:17)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
(anonymous) @ logic.js:50
update @ logic.js:46
getData @ logic.js:112
_render @ foundry.js:5108
render @ foundry.js:5067
render @ logic.js:159
(anonymous) @ party-overview.js:62
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
logic.js:50 Error: Couldn't load actor 'Leeroy' (ID: 'd3AlIbIAu0AET7TF') TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at archmageProvider.getActorDetails (SystemProvider.js:134:10)
    at logic.js:48:46
    at Array.map (<anonymous>)
    at PartyOverviewApp.update (logic.js:46:19)
    at PartyOverviewApp.getData (logic.js:112:8)
    at PartyOverviewApp._render (foundry.js:5108:29)
    at PartyOverviewApp.render (foundry.js:5067:10)
    at PartyOverviewApp.render (logic.js:159:9)
    at HTMLButtonElement.<anonymous> (party-overview.js:62:17)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
(anonymous) @ logic.js:50
update @ logic.js:46
getData @ logic.js:112
_render @ foundry.js:5108
render @ foundry.js:5067
render @ logic.js:159
(anonymous) @ party-overview.js:62
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:747 TypeError: An error occurred while rendering PartyOverviewApp 1. Cannot convert undefined or null to object
[Detected 1 package: party-overview]
    at Function.keys (<anonymous>)
    at SystemProvider.js:172:11
    at Array.forEach (<anonymous>)
    at archmageProvider.getUpdate (SystemProvider.js:171:10)
    at PartyOverviewApp.update (logic.js:61:45)
    at PartyOverviewApp.getData (logic.js:112:8)
    at PartyOverviewApp._render (foundry.js:5108:29)
    at PartyOverviewApp.render (foundry.js:5067:10)
    at PartyOverviewApp.render (logic.js:159:9)
    at HTMLButtonElement.<anonymous> (party-overview.js:62:17)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)`

And this is what I got with just Party Overview enabled:
`Foundry VTT | Rendering PartyOverviewApp
logic.js:50 Error: Couldn't load actor 'Crumbling Skeleton' (ID: 'P3t8OSl4HhWS0UZl') TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at archmageProvider.getActorDetails (SystemProvider.js:134:10)
    at logic.js:48:46
    at Array.map (<anonymous>)
    at PartyOverviewApp.update (logic.js:46:19)
    at PartyOverviewApp.getData (logic.js:112:8)
    at PartyOverviewApp._render (foundry.js:5108:29)
    at PartyOverviewApp.render (foundry.js:5067:10)
    at PartyOverviewApp.render (logic.js:159:9)
    at HTMLButtonElement.<anonymous> (party-overview.js:62:17)
(anonymous) @ logic.js:50
update @ logic.js:46
getData @ logic.js:112
_render @ foundry.js:5108
render @ foundry.js:5067
render @ logic.js:159
(anonymous) @ party-overview.js:62
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
logic.js:50 Error: Couldn't load actor 'Leeroy' (ID: 'd3AlIbIAu0AET7TF') TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at archmageProvider.getActorDetails (SystemProvider.js:134:10)
    at logic.js:48:46
    at Array.map (<anonymous>)
    at PartyOverviewApp.update (logic.js:46:19)
    at PartyOverviewApp.getData (logic.js:112:8)
    at PartyOverviewApp._render (foundry.js:5108:29)
    at PartyOverviewApp.render (foundry.js:5067:10)
    at PartyOverviewApp.render (logic.js:159:9)
    at HTMLButtonElement.<anonymous> (party-overview.js:62:17)
(anonymous) @ logic.js:50
update @ logic.js:46
getData @ logic.js:112
_render @ foundry.js:5108
render @ foundry.js:5067
render @ logic.js:159
(anonymous) @ party-overview.js:62
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:747 TypeError: An error occurred while rendering PartyOverviewApp 1. Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at SystemProvider.js:172:11
    at Array.forEach (<anonymous>)
    at archmageProvider.getUpdate (SystemProvider.js:171:10)
    at PartyOverviewApp.update (logic.js:61:45)
    at PartyOverviewApp.getData (logic.js:112:8)
    at PartyOverviewApp._render (foundry.js:5108:29)
    at PartyOverviewApp.render (foundry.js:5067:10)
    at PartyOverviewApp.render (logic.js:159:9)
    at HTMLButtonElement.<anonymous> (party-overview.js:62:17)`

Overall, it seems to not like the minions, which is strange. When I remove the ownership from the minions, it breaks the process. As I've mentioned, in the original 2.15 this isn't the case.

**Comment by mclemente** [comment]
Doesn't that player have a character? Your player has picked the skeleton as their character on the User Configuration for whatever reason, just release it and pick their actual character.
The module assumes users would pick only characters, not NPCs. They lack data such as coins, recoveries, backgrounds and icons.

**Comment by NikolaSama** [comment]
The player has a character (a Necromancer) and as that character he has access to summons and a skeletal minion. Regardless, it's still a fact that in version 2.15 the module recognizes that the NPC sheet isn't needed in the overview, regardless of ownership. It's somewhere between 2.15.1-2.15.7 that the issue appears. I can just continue using version 2.15, since it seems to be perfectly fine.

**Comment by NikolaSama** [comment]
Oh, the NPC isn't set as his default character.
![image](https://user-images.githubusercontent.com/6267543/225452953-46dbfacc-be54-45e8-9974-34d80e306cf5.png)

I'm rather careful in that regard, when I setup my games. Thank you for the fix, although I don't see how else I'm supposed to have summons/minions available to the player, if not by giving them ownership of the sheet.
![image](https://user-images.githubusercontent.com/6267543/225453290-36755641-fca0-4a25-8f60-c6483a0fbcbe.png)

**Comment by mclemente** [comment]
Then the issue was probably the view mode was set to the ALL mode, it saved that as the last mode and immediately broke. That was the only change between 2.15 to now that would do that.
