### ISSUE TITLE
Party Overview not displaying - logic.js:50 Error: Couldn't load actor Cal (ID: PBpgoKITS2GFEoOE) Error: The Set#map operation illegally modified the size of the set

### ISSUE THREAD

**Issue by kiloforce** [mclemente/party-overview#79]
Something in my world is causing Party Overview to break.  I created a clean world and Party Overview loads.  When I try to open Party Overview in my world, it doesn't pop up.  When I look at the Javascript console I get the below error.  Worried that it might be a module conflict I disabled all modules except for Party Overview, and I still get this error.  I repeats for every player.

```
Error: Couldn't load actor Cal (ID: PBpgoKITS2GFEoOE) Error: The Set#map operation illegally modified the size of the set
    at Set.map (commons.js:3592:13)
    at dnd5eProvider.getActorDetails (SystemProvider.js:594:67)
    at logic.js:48:46
    at Array.map (<anonymous>)
    at PartyOverviewApp.update (logic.js:46:19)
    at PartyOverviewApp.getData (logic.js:116:8)
    at PartyOverviewApp._render (foundry.js:5812:29)
    at PartyOverviewApp.render (foundry.js:5769:10)
    at PartyOverviewApp.render (logic.js:163:9)
    at HTMLButtonElement.<anonymous> (party-overview.js:59:22)

... repeats for each character ...

foundry.js:753 TypeError: An error occurred while rendering PartyOverviewApp 58. undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at SystemProvider.js:605:69
    at Array.reduce (<anonymous>)
    at dnd5eProvider.getUpdate (SystemProvider.js:605:5)
    at PartyOverviewApp.update (logic.js:61:45)
    at PartyOverviewApp.getData (logic.js:116:8)
    at PartyOverviewApp._render (foundry.js:5812:29)
    at PartyOverviewApp.render (foundry.js:5769:10)
    at PartyOverviewApp.render (logic.js:163:9)
    at HTMLButtonElement.<anonymous> (party-overview.js:59:22)
```

DnD5e world.  Foundry Version 11 Build 315.  Party Overview v2.16.5.  Characters were imported using DnDBeyond Importer.

**Comment by kiloforce** [comment]
Never mind, I went to my "new world" and simply started adding things to my new characters, such as adding languages, and ran into the same errors as the above, when trying to display "Party Overview".  Looks like Party Overview is very much broken, even on a clean world.

**Comment by kiloforce** [comment]
Perfect, thank you!
